### ISSUE TITLE
mappers_parsing_exception when indexing TextFields

### ISSUE THREAD

**Issue by fsecada01** [sabricot/django-elasticsearch-dsl#107]
I ran into this problem when trying to index varchar/LongText fields from my Django model.  They would index w/o any issues when using HayStack but there seems to be an issue when using this module.

`PUT http://localhost:9200/bottoms_up_jobs [status:400 request:0.016s]
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\dev\dbViewer\lib\site-packages\django\core\management\__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "C:\dev\dbViewer\lib\site-packages\django\core\management\__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\dev\dbViewer\lib\site-packages\django\core\management\base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\dev\dbViewer\lib\site-packages\django\core\management\base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "C:\dev\dbViewer\lib\site-packages\django_elasticsearch_dsl\management\commands\search_index.py", line 134, in handle
    self._rebuild(models, options)
  File "C:\dev\dbViewer\lib\site-packages\django_elasticsearch_dsl\management\commands\search_index.py", line 114, in _rebuild
    self._create(models, options)
  File "C:\dev\dbViewer\lib\site-packages\django_elasticsearch_dsl\management\commands\search_index.py", line 84, in _create
    index.create()
  File "C:\dev\dbViewer\lib\site-packages\elasticsearch_dsl\index.py", line 203, in create
    self.connection.indices.create(index=self._name, body=self.to_dict(), **kwargs)
  File "C:\dev\dbViewer\lib\site-packages\elasticsearch\client\utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "C:\dev\dbViewer\lib\site-packages\elasticsearch\client\indices.py", line 91, in create
    params=params, body=body)
  File "C:\dev\dbViewer\lib\site-packages\elasticsearch\transport.py", line 314, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "C:\dev\dbViewer\lib\site-packages\elasticsearch\connection\http_urllib3.py", line 180, in perform_request
    self._raise_error(response.status, raw_data)
  File "C:\dev\dbViewer\lib\site-packages\elasticsearch\connection\base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, 'mapper_parsing_exception', 'No handler for type [text] declared on field [Organization]')`

```
from django_elasticsearch_dsl import DocType, Index, fields
from .models import Bottoms_Up_Job, Organization

bottoms_up_job = Index('bottoms_up_jobs')
bottoms_up_job.settings(
	number_of_shards =1,
	number_of_replicas = 0,
	# tokenizer 	= 'classic',
	# analyzer 	= 'standard',
	)
# bottoms_up_job.mapping(



# 	)

@bottoms_up_job.doc_type
class JobDocument(DocType):
	job_post = fields.ObjectField(properties={
		'PostDate': fields.StringField(),
		'Job_Title': fields.StringField(),
		'Organization': fields.StringField(),
		'Location': fields.StringField(),
		# 'Job_Description': fields.TextField(),
		})

	class Meta:
		model = Bottoms_Up_Job
		fields = [
			'PostDate',
			'JobTitle',
			# 'Organization',
			'Location',
			# 'JobDesc'
		]

	queryset_pagination = 50

class OrganizationDocument(DocType):
	class Meta:
		model = Organization
		fields = [
			'Organization',
		]


```

**Comment by fsecada01** [comment]
Nevermind.  The issue was caused by the module's v6 running against the service being at 2.5.4.  I had forgotten to update the backend on windows before migrating, so I basically pulled a Homer Simpson.  Doh!
