### ISSUE TITLE
config custom analyzer related to char_filter

### ISSUE THREAD

**Issue by zsk1993** [sabricot/django-elasticsearch-dsl#129]
I want to use elasticsearch-analysis-stconvert in django,but I dont't how to config:
just like this:
html_strip = analyzer(
    'ik',
    tokenizer="ik_smart",
    filter=["standard", "lowercase", "stop", "snowball"],
    # char_filter=["html_strip"]
    char_filter=["tsconvert"]
)

html_filter = char_filter(
    'tsconvert',
    type="stconvert",
    convert_type="t2s"

)

But here are errors:
Traceback (most recent call last):
  File "./manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "E:\codes\xtsearch\venv\lib\site-packages\django\core\management\__init__.py", line 371, in execute_from_command_line
    utility.execute()
  File "E:\codes\xtsearch\venv\lib\site-packages\django\core\management\__init__.py", line 365, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "E:\codes\xtsearch\venv\lib\site-packages\django\core\management\base.py", line 288, in run_from_argv
    self.execute(*args, **cmd_options)
  File "E:\codes\xtsearch\venv\lib\site-packages\django\core\management\base.py", line 335, in execute
    output = self.handle(*args, **options)
  File "E:\codes\xtsearch\django_elasticsearch_dsl\management\commands\search_index.py", line 134, in handle
    self._rebuild(models, options)
  File "E:\codes\xtsearch\django_elasticsearch_dsl\management\commands\search_index.py", line 114, in _rebuild
    self._create(models, options)
  File "E:\codes\xtsearch\django_elasticsearch_dsl\management\commands\search_index.py", line 84, in _create
    index.create()
  File "E:\codes\xtsearch\elasticsearch_dsl\index.py", line 203, in create
    self.connection.indices.create(index=self._name, body=self.to_dict(), **kwargs)
  File "E:\codes\xtsearch\elasticsearch\client\utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "E:\codes\xtsearch\elasticsearch\client\indices.py", line 91, in create
    params=params, body=body)
  File "E:\codes\xtsearch\elasticsearch\transport.py", line 314, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "E:\codes\xtsearch\elasticsearch\connection\http_urllib3.py", line 180, in perform_request
    self._raise_error(response.status, raw_data)
  File "E:\codes\xtsearch\elasticsearch\connection\base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception', 'Custom Analyzer [ik] failed to find char_filter under name [tsconvert]')

**Comment by barseghyanartur** [comment]
You obviously need to properly install ``elasticsearch-analysis-stconvert`` before using it. This is out of the scope of this project.

**Comment by safwanrahman** [comment]
Out of scope!
