### ISSUE TITLE
Using Objectfield- VariableLookupError for self

### ISSUE THREAD

**Issue by yarnball** [sabricot/django-elasticsearch-dsl#13]
Hi,

I am trying to return data from a function, but keep getting a "VariableLookupError" for my function `for key [self]`.

I have tried both the `NestedField` and `ObjectField` options. Both gave the same traceback (as per below).

How can I fix the lookup error?

# documents.py
```
vehicle = Index('vehicle')

vehicle.settings(
    number_of_shards=1,
    number_of_replicas=0
)

@vehicle.doc_type
class VehicalDocument(DocType):
    tag = fields.ObjectField(attr="self.get_grouped_tags")
    class Meta:
        model = Vehicle
        fields = [
            'name'
        ] 
```

# models.py
```
class Tag(models.Model):
    name = models.CharField("Name", max_length=5000, blank=True)
    taglevel = models.IntegerField("Tag level", null=True, blank=True)

class Vehicle(models.Model):
    title = models.CharField("Title", max_length=10000, blank=True)
    tag = models.ManyToManyField('Tag', blank=True)

    def get_grouped_tags(self):
        tag = self.tag.order_by('taglevel')
        grouped_tags = {
            tag_level: [
                { 'name': tag_of_level.name, 'taglevel': tag_of_level.taglevel, }
                for tag_of_level in tags_of_level
            ] for tag_level, tags_of_level
            in groupby(tag, lambda tag: tag.taglevel)
        }
        return grouped_tags
```

# Traceback
```
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/UserX/Dev/A51/Backend/Chat/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "/Users/UserX/Dev/A51/Backend/Chat/venv/lib/python2.7/site-packages/django/core/management/__init__.py", line 342, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/UserX/Dev/A51/Backend/Chat/venv/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/UserX/Dev/A51/Backend/Chat/venv/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/Users/UserX/Dev/A51/Backend/Chat/venv/lib/python2.7/site-packages/django_elasticsearch_dsl/management/commands/search_index.py", line 117, in handle
    self.handle(*args, **options)
  File "/Users/UserX/Dev/A51/Backend/Chat/venv/lib/python2.7/site-packages/django_elasticsearch_dsl/management/commands/search_index.py", line 124, in handle
    self._execute_doc_action(action, doc, options)
  File "/Users/UserX/Dev/A51/Backend/Chat/venv/lib/python2.7/site-packages/django_elasticsearch_dsl/management/commands/search_index.py", line 101, in _execute_doc_action
    doc.update(qs.iterator())
  File "/Users/UserX/Dev/A51/Backend/Chat/venv/lib/python2.7/site-packages/django_elasticsearch_dsl/documents.py", line 165, in update
    return self.bulk(actions, **kwargs)
  File "/Users/UserX/Dev/A51/Backend/Chat/venv/lib/python2.7/site-packages/django_elasticsearch_dsl/documents.py", line 147, in bulk
    refresh=refresh, **kwargs)
  File "/Users/UserX/Dev/A51/Backend/Chat/venv/lib/python2.7/site-packages/elasticsearch/helpers/__init__.py", line 190, in bulk
    for ok, item in streaming_bulk(client, actions, **kwargs):
  File "/Users/UserX/Dev/A51/Backend/Chat/venv/lib/python2.7/site-packages/elasticsearch/helpers/__init__.py", line 161, in streaming_bulk
    for bulk_actions in _chunk_actions(actions, chunk_size, max_chunk_bytes, client.transport.serializer):
  File "/Users/UserX/Dev/A51/Backend/Chat/venv/lib/python2.7/site-packages/elasticsearch/helpers/__init__.py", line 55, in _chunk_actions
    for action, data in actions:
  File "/Users/UserX/Dev/A51/Backend/Chat/venv/lib/python2.7/site-packages/django_elasticsearch_dsl/documents.py", line 163, in <genexpr>
    } for model in thing)
  File "/Users/UserX/Dev/A51/Backend/Chat/venv/lib/python2.7/site-packages/django_elasticsearch_dsl/documents.py", line 126, in prepare
    data[name] = prep_func(instance)
  File "/Users/UserX/Dev/A51/Backend/Chat/venv/lib/python2.7/site-packages/django_elasticsearch_dsl/fields.py", line 99, in get_value_from_instance
    objs = super(ObjectField, self).get_value_from_instance(instance)
  File "/Users/UserX/Dev/A51/Backend/Chat/venv/lib/python2.7/site-packages/django_elasticsearch_dsl/fields.py", line 59, in get_value_from_instance
    "{!r}".format(attr, instance)
django_elasticsearch_dsl.exceptions.VariableLookupError: Failed lookup for key [self] in <Vehicle: Test item One (Vehicle)>
```

**Comment by sabricot** [comment]
You don't declare the mapping for the ObjectField but i guess it is because your mapping is kind of dynamic ? it can be one time `{1: [{'taglevel': 1, 'name': Foo'}], 2: [{'taglevel': 2, 'name': Bar'}}` another time `{1: [{'taglevel': 1, 'name': Foo'}]}` and so on ?

You need to declare the mapping of your data in ObjectField, but as your data is formated now, it will not work.
 Can you put you data in a list of objects instead, like this ? 
`[{'find_name_1': 1, 'find_name_2': [{'taglevel': 1, 'name': Foo'}]}, {'find_name_1': 2', 'find_a_name_2': [{'taglevel': 2, 'name': Bar'}] } ]`

Sorry for the dummy example i don't know how to call these fields :)
Then you need to declare the mapping in Objectfield.
```
ObjectField(attr="get_grouped_tags", properties={
        'field_name_1': fields.IntergerField(),
        'field_name_2': fields.ObjectField(properties={
                'name': fields.IntergerField(),
                'tagLevel': fields.StringField(),
        }),
    }
)
```
I haven't test theses examples it's just some indications.
You probably shouldn't use a small library, not release on pip and with not many contrib/stargazers if you don't really know exactly what you want from it.
