### ISSUE TITLE
elasticsearch as primary datastore

### ISSUE THREAD

**Issue by initzx** [sabricot/django-elasticsearch-dsl#211]
Is it possible to use elasticsearch as the primary datastore with the help of this plugin? I tried to execute the example code `car.save()`, where car is a django model that is supposed to be mapped to a document. I received a traceback message saying that I did not have a table set up in my SQL database:

```Traceback (most recent call last):
  File "/home/init0/PycharmProjects/mid/miscvenv/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/init0/PycharmProjects/mid/miscvenv/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: polls_car

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/init0/PycharmProjects/mid/miscvenv/lib/python3.7/site-packages/django/db/models/base.py", line 741, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/init0/PycharmProjects/mid/miscvenv/lib/python3.7/site-packages/django/db/models/base.py", line 779, in save_base
    force_update, using, update_fields,
  File "/home/init0/PycharmProjects/mid/miscvenv/lib/python3.7/site-packages/django/db/models/base.py", line 870, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/init0/PycharmProjects/mid/miscvenv/lib/python3.7/site-packages/django/db/models/base.py", line 908, in _do_insert
    using=using, raw=raw)
  File "/home/init0/PycharmProjects/mid/miscvenv/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/init0/PycharmProjects/mid/miscvenv/lib/python3.7/site-packages/django/db/models/query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/init0/PycharmProjects/mid/miscvenv/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1335, in execute_sql
    cursor.execute(sql, params)
  File "/home/init0/PycharmProjects/mid/miscvenv/lib/python3.7/site-packages/django/db/backends/utils.py", line 99, in execute
    return super().execute(sql, params)
  File "/home/init0/PycharmProjects/mid/miscvenv/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/home/init0/PycharmProjects/mid/miscvenv/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/home/init0/PycharmProjects/mid/miscvenv/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/init0/PycharmProjects/mid/miscvenv/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/home/init0/PycharmProjects/mid/miscvenv/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/home/init0/PycharmProjects/mid/miscvenv/lib/python3.7/site-packages/django/db/backends/sqlite3/base.py", line 383, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: polls_car
```
Am I supposed to use this plugin in conjunction with an existing database, or am I just doing something wrong here?

**Comment by safwanrahman** [comment]
its not possible to use Elasticsearch as primary database with this package as its solely depend on django model. From my personal opinion, you should not use ES as primary DB because time by time you need to reindex.

**Comment by initzx** [comment]
is it possible to extract data from a model, and use elasticsearch-dsl to manually save the data? I don't know if there are any functions already built in django-elasticsearch-dsl

**Comment by safwanrahman** [comment]
@initzx What you are trying to achieve actually?

**Comment by initzx** [comment]
just as i described, I wish to use elasticsearch as my primary database. Don't ask me why, I've just been required to do so. Are there any ways of achieving this?

**Comment by safwanrahman** [comment]
@initzx In that case, you can create Document with `elasticsearch-dsl` package, then run `MyDocument.init()` and it will create an index to the Elasticsearch database. You can use `MyDocument(**kwargs).save()` to save the document object and `MyDocument.search()` to search through it.

**Comment by initzx** [comment]
yea that was the conclusion I also came to, thanks!

**Comment by alexgarel** [comment]
Maybe you should look at the work on [django nonrel engine](http://django-nonrel.org/), that is writing your own backend to Django. [elasticsearch-dsl](https://elasticsearch-dsl.readthedocs.io/) is however a good library to build upon.
