### ISSUE TITLE
Django server crashes if elasticsearch server goes down

### ISSUE THREAD

**Issue by shivamzxzx** [sabricot/django-elasticsearch-dsl#225]
My django server stops populating data in my database and start sending 500.I get the following error if by any means elasticsearch server stops.

WARNING:elasticsearch:POST http://xx.xx.xx.xx:9200/_bulk?refresh=true [status:N/A request:0.004s]
Traceback (most recent call last):
  File "/home/dev-django1/.virtualenvs/logic_srv/lib/python3.6/site-packages/django/db/models/query.py", line 487, in get_or_create
    return self.get(**lookup), False
  File "/home/dev-django1/.virtualenvs/logic_srv/lib/python3.6/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
backend_apps.event_related.event.models.DoesNotExist: Event matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dev-django1/.virtualenvs/logic_srv/lib/python3.6/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/home/dev-django1/.virtualenvs/logic_srv/lib/python3.6/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/home/dev-django1/.virtualenvs/logic_srv/lib/python3.6/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dev-django1/.virtualenvs/logic_srv/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 172, in perform_request
    response = self.pool.urlopen(method, url, body, retries=Retry(False), headers=request_headers, **kw)
  File "/home/dev-django1/.virtualenvs/logic_srv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/dev-django1/.virtualenvs/logic_srv/lib/python3.6/site-packages/urllib3/util/retry.py", line 343, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/dev-django1/.virtualenvs/logic_srv/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/home/dev-django1/.virtualenvs/logic_srv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/dev-django1/.virtualenvs/logic_srv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1254, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1300, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1249, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 974, in send
    self.connect()
  File "/home/dev-django1/.virtualenvs/logic_srv/lib/python3.6/site-packages/urllib3/connection.py", line 181, in connect
    conn = self._new_conn()
  File "/home/dev-django1/.virtualenvs/logic_srv/lib/python3.6/site-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f4138795710>: Failed to establish a new connection: [Errno 111] Connection refused
WARNING:elasticsearch:POST http://xx.xx.xx.xx:9200/_bulk?refresh=true [status:N/A request:0.001s]
Traceback (most recent call last):
  File "/home/dev-django1/.virtualenvs/logic_srv/lib/python3.6/site-packages/django/db/models/query.py", line 487, in get_or_create
    return self.get(**lookup), False
  File "/home/dev-django1/.virtualenvs/logic_srv/lib/python3.6/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
backend_apps.event_related.event.models.DoesNotExist: Event matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dev-django1/.virtualenvs/logic_srv/lib/python3.6/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/home/dev-django1/.virtualenvs/logic_srv/lib/python3.6/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/home/dev-django1/.virtualenvs/logic_srv/lib/python3.6/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dev-django1/.virtualenvs/logic_srv/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 172, in perform_request
    response = self.pool.urlopen(method, url, body, retries=Retry(False), headers=request_headers, **kw)
  File "/home/dev-django1/.virtualenvs/logic_srv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/dev-django1/.virtualenvs/logic_srv/lib/python3.6/site-packages/urllib3/util/retry.py", line 343, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/dev-django1/.virtualenvs/logic_srv/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/home/dev-django1/.virtualenvs/logic_srv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/dev-django1/.virtualenvs/logic_srv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1254, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1300, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1249, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 974, in send
    self.connect()
  File "/home/dev-django1/.virtualenvs/logic_srv/lib/python3.6/site-packages/urllib3/connection.py", line 181, in connect
    conn = self._new_conn()
  File "/home/dev-django1/.virtualenvs/logic_srv/lib/python3.6/site-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f41387a5e10>: Failed to establish a new connection: [Errno 111] Connection refused
WARNING:elasticsearch:POST http://xx.xx.xx.xx:9200/_bulk?refresh=true [status:N/A request:0.001s]
Traceback (most recent call last):
  File "/home/dev-django1/.virtualenvs/logic_srv/lib/python3.6/site-packages/django/db/models/query.py", line 487, in get_or_create
    return self.get(**lookup), False
  File "/home/dev-django1/.virtualenvs/logic_srv/lib/python3.6/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
backend_apps.event_related.event.models.DoesNotExist: Event matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dev-django1/.virtualenvs/logic_srv/lib/python3.6/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/home/dev-django1/.virtualenvs/logic_srv/lib/python3.6/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/home/dev-django1/.virtualenvs/logic_srv/lib/python3.6/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dev-django1/.virtualenvs/logic_srv/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 172, in perform_request
    response = self.pool.urlopen(method, url, body, retries=Retry(False), headers=request_headers, **kw)
  File "/home/dev-django1/.virtualenvs/logic_srv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/dev-django1/.virtualenvs/logic_srv/lib/python3.6/site-packages/urllib3/util/retry.py", line 343, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/dev-django1/.virtualenvs/logic_srv/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/home/dev-django1/.virtualenvs/logic_srv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/dev-django1/.virtualenvs/logic_srv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1254, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1300, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1249, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 974, in send
    self.connect()
  File "/home/dev-django1/.virtualenvs/logic_srv/lib/python3.6/site-packages/urllib3/connection.py", line 181, in connect
    conn = self._new_conn()
  File "/home/dev-django1/.virtualenvs/logic_srv/lib/python3.6/site-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f4137f165c0>: Failed to establish a new connection: [Errno 111] Connection refused
WARNING:elasticsearch:POST http://xx.xx.xx.xx:9200/_bulk?refresh=true [status:N/A request:0.001s]
Traceback (most recent call last):
  File "/home/dev-django1/.virtualenvs/logic_srv/lib/python3.6/site-packages/django/db/models/query.py", line 487, in get_or_create
    return self.get(**lookup), False
  File "/home/dev-django1/.virtualenvs/logic_srv/lib/python3.6/site-packages/django/db/models/query.py", line 403, in get
    self.model._meta.object_name
backend_apps.event_related.event.models.DoesNotExist: Event matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dev-django1/.virtualenvs/logic_srv/lib/python3.6/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/home/dev-django1/.virtualenvs/logic_srv/lib/python3.6/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/home/dev-django1/.virtualenvs/logic_srv/lib/python3.6/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dev-django1/.virtualenvs/logic_srv/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 172, in perform_request
    response = self.pool.urlopen(method, url, body, retries=Retry(False), headers=request_headers, **kw)
  File "/home/dev-django1/.virtualenvs/logic_srv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/dev-django1/.virtualenvs/logic_srv/lib/python3.6/site-packages/urllib3/util/retry.py", line 343, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/dev-django1/.virtualenvs/logic_srv/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/home/dev-django1/.virtualenvs/logic_srv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/dev-django1/.virtualenvs/logic_srv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1254, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1300, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1249, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 974, in send
    self.connect()
  File "/home/dev-django1/.virtualenvs/logic_srv/lib/python3.6/site-packages/urllib3/connection.py", line 181, in connect
    conn = self._new_conn()
  File "/home/dev-django1/.virtualenvs/logic_srv/lib/python3.6/site-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f4137f16550>: Failed to establish a new connection: [Errno 111] Connection refused
ERROR:backend_apps.event_related.event.views_dir.views_pzz:N/A

**Comment by safwanrahman** [comment]
Yes. Its a synchronous indexing and the django server will go down if the elasticsearch server stops. You need to manually handle the singals and everything if you want to index asynchronous.

**Comment by shivamzxzx** [comment]
@safwanrahman : Can you suggest how? or point to some similar issues. 
Elastic is our logging and data analysis server and we cant let our production server go down if there are any issues with the Elastic stack.
If there is any data loss on the elastic DB we are okay with it.
Thanks
