### ISSUE TITLE
TypeError: 'CustomUser' object is not subscriptable

### ISSUE THREAD

**Issue by khaldon** [sabricot/django-elasticsearch-dsl#267]
I need to get all courses that tutor that created. it gives me that error 
```
Traceback (most recent call last):
  File "/home/khaldon/anaconda3/envs/dj/lib/python3.7/site-packages/django_elasticsearch_dsl/fields.py", line 53, in get_value_from_instance
    instance = instance[attr]
TypeError: 'CustomUser' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/khaldon/anaconda3/envs/dj/lib/python3.7/site-packages/django_elasticsearch_dsl/fields.py", line 59, in get_value_from_instance
    instance = getattr(instance, attr)
AttributeError: 'CustomUser' object has no attribute 'description'
```

models.py
```
class Course(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=150, null=True, blank=True)
    description = models.TextField()
    tutor = models.ForeignKey(User,related_name='tutor_courses',on_delete=models.CASCADE)
```

documents.py
```
from django_elasticsearch_dsl import Document, fields
from django_elasticsearch_dsl.registries import registry
from .models import Course
from django.conf import settings
User = settings.AUTH_USER_MODEL


@registry.register_document
class CourseDocument(Document):
    tutor = fields.ObjectField(properties={
        'description':fields.TextField(),
        'title':fields.TextField(),
        'pk':fields.IntegerField(),
    })
    class Index:
        name='courses'
        settings= {'number_of_shards':1,'number_of_replicas':0}
    
    class Django:
        model = Course
        fields = [
            'title',
            'description',
        ]
        related_models = [User]
        def get_queryset(self):
            return super(CourseDocument, self).get_queryset().select_related(
                'tutor'
            )
        def get_instances_from_related(self, related_instance):
            if isinstance(related_instance, User):
                return related_instance.course_set.all()
```

**Comment by alexgarel** [comment]
Please, post that kind of question on stackoverflow with the django-elasticsearch-dsl tag.
Not here.
